repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
    - id: check-json
    - id: check-ast

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black
      args: [--line-length=88]

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: ["--profile", "black"]

- repo: https://github.com/PyCQA/docformatter
  rev: v1.7.0
  hooks:
    - id: docformatter
      args: [--in-place, --pre-summary-newline]
